<!DOCTYPE html>
<html <?php language_attributes(); ?>>
  <head>
    <meta charset="<?php bloginfo('charset'); ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <?php wp_head(); ?>

  </head>
  <body>
    <!--========== Start Header ==========-->
    <header class="header">
      <div class="container">
        <nav class="navbar">
          <a href="#" class="link navbar__brand text--light">
            <?php
              if (function_exists('the_custom_logo')) {
                the_custom_logo();
              } else {
                bloginfo('name');
              }
              
            ?>
          </a>

          <button class="navbar__toggle-button">
          <?xml version="1.0" encoding="utf-8"?>
<!-- Generated by IcoMoon.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" viewBox="0 0 20 20">
<path fill="#000000" d="M17.5 6h-15c-0.276 0-0.5-0.224-0.5-0.5s0.224-0.5 0.5-0.5h15c0.276 0 0.5 0.224 0.5 0.5s-0.224 0.5-0.5 0.5z"></path>
<path fill="#000000" d="M17.5 11h-15c-0.276 0-0.5-0.224-0.5-0.5s0.224-0.5 0.5-0.5h15c0.276 0 0.5 0.224 0.5 0.5s-0.224 0.5-0.5 0.5z"></path>
<path fill="#000000" d="M17.5 16h-15c-0.276 0-0.5-0.224-0.5-0.5s0.224-0.5 0.5-0.5h15c0.276 0 0.5 0.224 0.5 0.5s-0.224 0.5-0.5 0.5z"></path>
</svg>

          </button>

          <!-- Navigation Items -->
          <div class="navbar__collapse" id="toggle--collapse">
            <?php
              // Display Primary Menu
              if (has_nav_menu('primary-menu')) {
                wp_nav_menu(array(
                  'theme-location' => 'primary-menu',
                  'container' => 'ul',
                  'menu_class' => 'navbar__nav mr--auto',
                  'items_wrap' => '<ul class="%2$s">%3$s</ul>'
                ));
              }
            ?>
          <!--<ul class="navbar__nav">
              <li class="navbar__item">
                <a href="#" class="navbar__link text--light">Home</a>
              </li>
              <li class="navbar__item">
                <a href="#" class="navbar__link text--light">Berita</a>
              </li>
              <li class="navbar__item">
                <a href="#" class="navbar__link text--light">Galeri</a>
              </li>
              <li class="navbar__item">
                <a href="#" class="navbar__link text--light">Informasi</a>
              </li>
              <li class="navbar__item">
                <a href="#" class="navbar__link text--light">Tentang</a>
              </li>
            </ul>-->
          </div>
          <div class="search">
            <?php 
              // Get searchform.php template
              get_search_form(); 
            ?>

            <!--<form class="search__form">
              <input
                type="search"
                class="search__input mr--sm-2"
                placeholder="Cari"
              />
              <button class="btn btn--submit" type="submit">
                <img src="./vendors/icons/magnifier.svg" alt="icon search" />
              </button>
            </form>-->
          </div>
        </nav>
      </div>
    </header>
    <!--========== End Header ==========-->

    <!--========== Start Main ==========-->
    <main class="main">